language: php
dist: trusty
php:
  - 7.2
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'
before_script:
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan migrate --seed
script:
  - vendor/bin/phpunit --coverage-clover coverage.xml
notifications:
  email: false
  webhooks:
    urls:
      - https://misc.schrej.net/travistodiscord/pterodev.php
    on_success: change
    on_failure: always
    on_error: always
    on_cancel: always
    on_start: never
after_success:
  - bash <(curl -s https://codecov.io/bash)
